apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiremock.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wiremock.name" . }}
    helm.sh/chart: {{ include "wiremock.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.deployment.extraLabels }}
{{ toYaml .Values.deployment.extraLabels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wiremock.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.deployment.matchLables.extraLabels }}
{{ toYaml .Values.deployment.matchLables.extraLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/configMappings: {{ include (print $.Template.BasePath "/configmap-mappings.yaml") . | sha256sum }}
        checksum/configResponses: {{ include (print $.Template.BasePath "/configmap-responses.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "wiremock.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.deployment.template.extralabels }}
{{ toYaml .Values.deployment.template.extralabels | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
          {{- end }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ tpl $value $ | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__admin/webapp
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /__admin/webapp
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
          volumeMounts:
          - mountPath: /home/wiremock/storage/mappings
            name: mappings-volume
          - mountPath: /home/wiremock/storage/__files
            name: responses-volume
      volumes:
        - name: mappings-volume
          configMap:
            name: {{ include "wiremock.fullname" . }}-mappings-configs
        - name: responses-volume
          configMap:
            name: {{ include "wiremock.fullname" . }}-responses-configs